
#Explain the differences between standard output (stdout) and standard error (stderr).
#stdout:
#Used to display or output regular information generated by a program
# This includes the main results or data of a command's execution.
# stderr:
# Used to display error messages or diagnostics. 
#This allows programs to report issues separately from regular output.



#!/bin/bash

#Example Output (stderr):
# Here are examples of error output (stderr), which contains messages about problems or issues encountered by a command:

#1)
cat mai_file.txt
#Output (stderr):
#*******************************************#
#cat: mai_file.txt: No such file or directory
#*******************************************#
#2)
mkdir /restricted_folder

#*******************************************#
#mkdir: cannot create directory ‘/restricted_folder’: Permission denied
#*******************************************#
#3)
expr 5 / 0
#*******************************************#
#expr: division by zero
#*******************************************#



#Example Output (stdout):

# Listing Files
ls
#*******************************************#
#2
echo "Welcome to the Bash shell!"


#3)
#*******************************************#
cat test.txt

#4)
#Searching for a String in a File
grep "example" file1.txt


chmod +x Differences_stdout_stderr.sh